/**
 * 확정 전 초안 문구.
 *
 * 기준 문서에 없는 문구를 여기에 모은다. 화면 코드는 이 값을 읽고, 초안 문구를 직접 적지 않는다.
 * 문구가 확정되면 서정의 확인을 받아 값을 고친다.
 * 기준 문서에 원문이 있는 확정 문구는 여기에 두지 않고 confirmed-copy.ts에 근거와 함께 둔다.
 */
export const draftCopy = {
  /** 로그인·회원가입 (⑤). 어떤 행동 때문에 로그인하는지에 따라 이유 문구가 달라진다 */
  login: {
    titleLogin: '로그인',
    titleSignup: '회원가입',
    reasonOrder: '주문하려면 로그인이 필요해요. 장바구니는 그대로 있어요.',
    reasonFavorite: '찜하려면 로그인이 필요해요.',
    reasonAccount: '계좌를 등록하려면 로그인이 필요해요.',
    reasonDefault: '로그인하고 이어서 이용해보세요.',
    emailLabel: '이메일',
    emailPlaceholder: 'example@email.com',
    passwordLabel: '비밀번호',
    passwordPlaceholder: '비밀번호',
    passwordHelpSignup: '8자 이상 입력해주세요',
    emailError: '이메일 형식을 확인해주세요',
    passwordError: '비밀번호를 입력해주세요',
    passwordTooShort: '8자 이상 입력해주세요',
    failedTitle: '이메일 또는 비밀번호를 확인해주세요',
    failedDesc: '장바구니는 그대로 있어요.',
    networkFailedTitle: '로그인하지 못했어요. 인터넷 연결을 확인하고 다시 시도해주세요.',
    forgotPassword: '비밀번호를 잊으셨나요?',
    ctaLogin: '로그인',
    ctaSignup: '가입하고 계속하기',
    switchToSignup: '처음이에요 · 회원가입',
    switchToLogin: '이미 계정이 있어요 · 로그인',
    toastLoggedIn: '로그인했어요',
    toastSignedUp: '가입했어요',
  },

  /** 내역 (⑪ ⑬ ⑮) */
  history: {
    title: '내역',
    guestTitle: '로그인하면 주문 내역을 볼 수 있어요',
    guestDesc: '주문 완료가 필요한 주문도\n여기서 이어갈 수 있어요.',
    guestAction: '로그인',
    reasonHistory: '내역을 보려면 로그인이 필요해요.',
    loadErrorTitle: '내역을 불러오지 못했어요',
    emptyTitle: '아직 SaveEats 주문이 없어요',
    emptyAction: '메뉴 둘러보기',
    loadingMore: '더 불러오는 중',
    pageErrorText: '더 불러오지 못했어요',
    pageErrorRetry: '다시 시도',
    end: '주문 내역을 모두 봤어요',
    refreshFailed: '내역을 새로 불러오지 못했어요',
    detail: '주문 상세',
    resume: '주문 이어하기',
    retrySave: '상태 저장 다시 시도',
    resumeBusy: '진행 중인 주문 처리가 끝난 뒤에 이어갈 수 있어요',
    resumeFailed: '주문 상태를 확인하지 못했어요. 다시 시도해주세요.',
    resumeAlreadyDone: '이 주문은 이미 상태가 바뀌었어요',
    sameMenu: '같은 메뉴 보기',
    unreadLabel: '확인하지 않은 주문 상태 업데이트가 있어요',
    statusPending: '주문 완료가 필요해요',
    statusSaveFailed: '완료 확인을 저장하지 못했어요',
    statusCancelled: '주문이 취소됐어요',
    delivered: (amountLabel: string) => `내 계좌로 ${amountLabel} 배달`,
    detailTitle: '주문 상세',
    detailItemsLabel: '주문 메뉴',
    detailOrderedAt: '주문 시각',
    detailDoneAt: '완료 시각',
    detailCancelledAt: '취소 시각',
    detailAmount: '주문금액',
    detailDestinationDone: '돈이 배달된 곳',
    detailDestinationPending: '돈이 배달될 곳',
    detailStatus: '상태',
    detailStatusPending: '주문 완료가 필요해요',
    detailStatusDone: '주문 완료',
    detailStatusCancelled: '주문 취소',
    detailReviewHeading: 'SaveEats 리뷰',
    detailReviewHelp: '리뷰는 주문 완료 후 30일 동안 작성할 수 있어요.',
    detailLoadErrorTitle: '주문 정보를 불러오지 못했어요',
    summaryThisMonth: '이번 달',
    summaryNone: '아직 주문 완료가 없어요',
    summaryError: '이번 달 요약을 불러오지 못했어요',
    summaryOrders: (n: number) => `${n}번`,
    summaryDelivered: (amountLabel: string) => `내 계좌로 ${amountLabel} 배달`,
    monthlyTitle: '이번 달 요약',
    monthlyHeading: (month: number) => `${month}월의 SaveEats`,
    monthlyEmpty: '이 달에는 주문 완료 기록이 없어요',
    monthlyErrorTitle: '요약을 불러오지 못했어요',
    monthlyErrorDesc: '다시 시도해주세요.',
    monthlyHelp: '주문 완료 기준이에요. 완료가 필요한 주문과 취소한 주문은 세지 않아요.',
    monthlyOrders: '주문 완료',
    monthlyDelivered: '내 계좌로 배달된 금액',
    monthlyTopFood: '가장 많이 고른 음식',
    monthlyLargest: '가장 큰 주문',
    prevMonth: '이전 달',
    nextMonth: '다음 달',
  },

  /** 리뷰 (⑯ ⑰ ⑱ ⑳). 기준 문서에 원문이 있는 문구는 confirmed-copy.ts */
  review: {
    loading: '리뷰를 불러오는 중',
    loadErrorTitle: '리뷰를 불러오지 못했어요',
    loadErrorDescInStore: '메뉴는 그대로 볼 수 있어요.',
    noReviews: '아직 리뷰가 없어요',
    noPhotoReviews: '사진 리뷰가 아직 없어요',
    photoFilter: '사진 리뷰',
    sortSheetTitle: '리뷰 정렬',
    loadMore: '리뷰 더 보기',
    loadMoreFailed: '더 불러오지 못했어요',
    loadMoreRetry: '다시 시도',
    countLabel: (n: string) => `SaveEats 리뷰 ${n}`,
    averageLabel: '땡김도',
    manageEdit: '리뷰 수정',
    manageDelete: '리뷰 삭제',
    manageCancel: '취소',
    deleting: '삭제하는 중',
    deleteConfirm: '삭제하기',
    deleteFailed: '리뷰를 삭제하지 못했어요. 다시 시도해주세요.',
    helpfulFailed: '도움돼요를 저장하지 못했어요. 다시 시도해주세요.',
    helpfulLoginReason: '도움돼요를 누르려면 로그인이 필요해요.',
    reportSheetTitle: '리뷰 신고',
    reportReasons: ['부적절한 표현이 있어요', '광고·홍보 글이에요', '개인정보가 들어 있어요'],
    reportOpen: '리뷰 신고',
    moreOpen: '내 리뷰 관리',
    menuLineLoadFailed: '리뷰를 불러오지 못했어요',
    menuLineRetry: '다시 시도',
    orderCompleted: '주문 완료',
    edited: '수정됨',
    created: '리뷰를 등록했어요',
    updated: '리뷰를 수정했어요',
    mineTitle: '내가 쓴 리뷰',
    alreadyWritten: '이 주문에는 이미 쓴 리뷰가 있어요',
    viewMine: '내가 쓴 리뷰 보기',
    reloadLatest: '돌아가기',
    mineLoadErrorTitle: '내가 쓴 리뷰를 불러오지 못했어요',
    mineLoading: '리뷰를 불러오는 중',
    write: {
      createTitle: '리뷰 쓰기',
      editTitle: '리뷰 수정',
      ratingLabel: '땡김도',
      required: '필수',
      ratingHint: '얼마나 먹고 싶었는지 골라주세요',
      ratingValue: (n: number) => `땡김도 ${n}`,
      ratingError: '땡김도를 선택해주세요',
      bodyLabel: '리뷰',
      bodyPlaceholder: '이 메뉴가 왜 땡겼는지 들려주세요',
      bodyTooShort: (min: number) => `${min}자 이상 써주세요`,
      bodyTooLong: (max: number) => `${max}자까지 쓸 수 있어요`,
      photoLabel: '사진',
      photoOptional: '선택 · 최대 1장',
      photoAdd: '사진 추가',
      photoUploading: '사진을 올리는 중이에요',
      photoFailedDesc: '입력한 땡김도와 글은 그대로 있어요.',
      photoRetry: '다시 시도',
      photoRemove: '사진 빼기',
      photoBlockedNote: '사진을 다시 올리거나 빼면 등록할 수 있어요',
      ctaCreate: '리뷰 등록하기',
      ctaCreating: '등록하는 중',
      ctaUpdate: '수정 완료',
      ctaUpdating: '저장하는 중',
      helpEdit: '주문·가게·메뉴·금액은 바꿀 수 없어요. 수정해도 받은 도움돼요는 그대로예요.',
      blockedDesc: '리뷰는 주문 완료 후 30일 동안 작성할 수 있어요.',
      saveFailedDesc: '입력한 내용은 그대로 있어요.',
      loadErrorTitle: '주문 정보를 불러오지 못했어요',
      loadErrorTitleEdit: '리뷰를 불러오지 못했어요',
    },
  },

  /** 계좌 관리·등록·완료 (⑥) */
  account: {
    manageTitle: '돈이 배달될 계좌',
    manageHelp: '지금은 계좌를 1개만 등록할 수 있어요.',
    change: '계좌 변경',
    remove: '계좌 삭제',
    pendingOrderNotice: '진행 중인 주문은 주문 당시 계좌로 이어가요',
    deleteTitle: '계좌를 삭제할까요?',
    deleteDesc: '삭제하면 다시 등록하기 전까지 주문할 수 없어요.',
    deleteConfirm: '삭제하기',
    toastDeleted: '계좌를 삭제했어요',
    toastChanged: '계좌를 변경했어요',
    formTitleRegister: '계좌 등록',
    formTitleChange: '계좌 변경',
    formHeadingRegister: '주문금액이 도착할 계좌를 등록해주세요.',
    formHeadingChange: '주문금액을 새로 받을 계좌를 입력해주세요.',
    bankLabel: '은행',
    bankPlaceholder: '은행을 선택해주세요',
    bankSheetTitle: '은행 선택',
    bankError: '은행을 선택해주세요',
    numberLabel: '계좌번호',
    numberPlaceholder: '숫자만 입력',
    numberHelp: "'-' 없이 숫자만 입력해주세요",
    numberError: '계좌번호를 끝까지 입력해주세요',
    maskGuide: '등록한 계좌는 토스뱅크 •••• 1234처럼 끝 4자리만 보여요.',
    ctaRegister: '계좌 등록하기',
    ctaChange: '계좌 변경하기',
    saveFailedTitle: '계좌를 등록하지 못했어요. 다시 시도해주세요.',
    saveFailedDesc: '입력한 내용은 그대로 있어요.',
    doneFromOrderGuide: '장바구니는 그대로 있어요. 주문을 이어서 확인해주세요.',
    doneCtaOrder: '주문 계속하기',
    doneCtaManage: '확인',
  },

  /** 최종 주문 확인 (⑦) */
  confirm: {
    title: '주문 확인',
    itemsLabel: '주문 메뉴',
    destinationLabel: '돈이 배달될 곳',
    cta: (amountLabel: string) => `${amountLabel} 내 계좌로 주문하기`,
    ctaSending: '주문 보내는 중',
    otherWay: '다른 방법으로 주문하기',
    createUnknownTitle: '주문이 만들어졌는지 확인하지 못했어요',
    createUnknownDesc: '같은 주문으로 다시 확인할게요. 새 주문은 만들지 않아요.',
    createUnknownAction: '다시 확인',
    localSaveFailedTitle: '주문 요청을 저장하지 못했어요. 다시 시도해주세요.',
    localSaveFailedDesc: '아직 주문은 만들어지지 않았고 외부 앱도 열리지 않았어요.',
    rejectedTitle: '가격이 바뀌었거나 품절된 메뉴가 있어요',
    rejectedDesc: '장바구니에서 확인한 뒤 다시 주문해주세요.',
    rejectedAction: '장바구니로',
    accountRequiredTitle: '계좌를 확인해주세요',
    accountRequiredDesc: '등록된 계좌가 바뀌었거나 없어요. 계좌를 확인한 뒤 다시 주문해주세요.',
  },

  /** 주문 이어가기·직접 이어가기 (⑧) */
  transfer: {
    continueTitle: '주문 이어가기',
    continueGuide: '토스에서 주문금액을 보낸 뒤 SaveEats로 돌아오면 주문을 완료할 수 있어요.',
    continueCta: '토스로 주문 이어가기',
    directTitle: '직접 주문 이어가기',
    otherWaySheetTitle: '다른 방법으로 주문하기',
    otherWayOptionTitle: '직접 주문 이어가기',
    otherWayOptionSub: '계좌번호와 금액을 복사해 사용 중인 금융앱에서 보내요',
    destinationLabel: '돈이 배달될 곳',
    amountLabel: '주문금액',
    copyAccount: '계좌번호 복사',
    copyAmount: '금액 복사',
    openToss: '토스 열기',
    rawUnavailable: '계좌 정보를 확인하지 못했어요',
    rawRetry: '다시 확인',
    copyFailed: '복사하지 못했어요. 다시 시도해주세요.',
    kvStore: '가게',
    kvMenus: '주문 메뉴',
    kvAmount: '주문금액',
    kvDestination: '돈이 배달될 곳',
    kvDelivered: '돈이 배달된 곳',
  },

  /** 복귀 후 확인·완료·취소 (⑨ ⑩) */
  result: {
    returnChecking: '주문 상태를 확인하고 있어요',
    questionGuide: '토스나 사용 중인 금융앱에서 주문금액을 보냈다면 주문 완료를 눌러주세요.',
    notYet: '아직이에요',
    confirmDone: '주문 완료했어요',
    cancelOrder: '주문 취소',
    confirmSaveFailedTitle: '완료 확인을 저장하지 못했어요',
    cancelUnknownTitle: '주문 취소를 확인하지 못했어요',
    cancelUnknownDesc: '취소됐는지 다시 확인할게요.',
    cancelUnknownAction: '다시 확인',
    statusErrorDesc: '다시 시도하거나 내역에서 확인해주세요.',
    toHistory: '내역 보기',
    notYetTitle: '주문은 그대로 남아 있어요',
    notYetDesc: "내역에서 '주문 이어하기'로 언제든 이어갈 수 있어요.",
    notYetResume: '주문 이어가기',
    doneHeader: '주문 완료 🎉', // 기획서 22: 이모지는 이 헤더만 예외
    doneReview: 'SaveEats 리뷰 남기기',
    cancelledDesc: '이 주문은 내역에 취소로 남아요. 이미 보낸 돈은 취소되지 않아요.',
    /** ORD-009 제안 문구 그대로. 제품 검수 필요 */
    cancelSheetTitle: 'SaveEats 주문 기록을 취소할까요?',
    cancelSheetDesc: '이미 보낸 돈은 취소되지 않아요.',
    cancelSheetBack: '돌아가기',
    cancelSheetConfirm: '주문 취소',
  },

  /** 아직 디자인이 없는 화면의 빈 화면 한 줄 (docs/design.md "아직 디자인이 없는 화면") */
  unbuiltScreen: '아직 준비 중인 화면이에요',

  /** 다음 단계(묶음 2~4)에서 연결될 버튼을 눌렀을 때의 임시 안내. 화면이 연결되면 쓰지 않는다 */
  pendingNextStep: '이 화면은 아직 연결되지 않았어요',

  home: {
    sectionError: '가게를 불러오지 못했어요',
    categoriesError: '카테고리를 불러오지 못했어요',
    recentTitle: '최근 본 가게·메뉴',
    recentKindStore: '가게',
    recentKindMenu: '메뉴',
    recommendedTitle: '추천 가게',
  },

  store: {
    loadErrorTitle: '가게 정보를 불러오지 못했어요',
    noMenus: '아직 등록된 메뉴가 없어요',
    /** 계약 isOpen 값의 표시 문구. "준비 중"은 디자인 시안, 10/1 결정 문서는 "영업 종료"라고 부른다 */
    statusOpen: '영업 중',
    statusClosed: '준비 중',
  },

  menu: {
    ruleSingle: '1개 선택',
    ruleMax: (max: number) => `최대 ${max}개까지 고를 수 있어요`,
    ruleFull: (max: number) => `${max}개 모두 골랐어요`,
    quantityHelp: (max: number) => `최대 ${max}개`,
    noteSoldOut: '품절된 메뉴라 지금은 담을 수 없어요',
    noteLoading: '옵션 정보를 불러온 뒤 담을 수 있어요',
    noteMissingRequired: (groupName: string) => `필수 옵션을 골라주세요 · ${groupName}`,
    /** 영업 종료 가게 담기 차단 안내 (10/1 결정 문구). UNDECIDED.preparingStoreOrderable이 false일 때만 쓴다 */
    noteStoreClosed: '지금은 영업이 종료됐어요',
    /** 디자인 시안 문구. 10/1 결정 문서의 문구는 "한 메뉴는 최대 10개까지 담을 수 있어요." */
    toastOverLimit: '같은 메뉴는 최대 10개까지 담을 수 있어요',
    toastAdded: '장바구니에 담았어요',
    toastAddedAction: '보기',
  },

  cart: {
    /** 장바구니 저장 실패 문구는 개발 명세 CART-003 원문 */
    saveFailed: '장바구니를 저장하지 못했어요. 다시 시도해주세요.',
    emptyTitle: '장바구니가 비어 있어요',
    emptyDescription: '먹고 싶은 메뉴를 골라 주문하면\n주문금액이 내 계좌로 배달돼요.',
    emptyAction: '메뉴 둘러보기',
    clearTitle: '장바구니를 비울까요?',
    clearDesc: '담긴 메뉴가 모두 삭제돼요.',
    clearConfirm: '비우기',
    priceChangedTitle: (count: number) => `가격이 바뀐 메뉴가 ${count}개 있어요`,
    priceChangedDesc: '바뀐 가격을 확인해야 주문할 수 있어요.',
    priceChangedAction: '확인',
    priceChangedLine: '가격이 바뀌었어요',
    soldOutTitle: '품절된 메뉴가 있어요',
    soldOutDesc: '품절된 메뉴를 삭제한 뒤 주문할 수 있어요.',
    inactiveTitle: '지금 주문할 수 없는 메뉴가 있어요',
    inactiveDesc: '판매하지 않는 메뉴를 삭제한 뒤 주문할 수 있어요.',
    optionsInvalidTitle: '옵션을 다시 골라야 하는 메뉴가 있어요',
    optionsInvalidDesc: '해당 메뉴를 삭제한 뒤 주문할 수 있어요.',
    storeClosedTitle: '지금은 영업이 종료됐어요',
    storeClosedDesc: '영업 중일 때 주문할 수 있어요.',
    storageErrorTitle: '장바구니를 불러오지 못했어요',
    storageErrorDesc: '저장된 장바구니를 읽을 수 없어요. 비우고 다시 담아주세요.',
    storageErrorAction: '비우기',
    itemMenuSoldOut: '품절된 메뉴예요',
    itemOptionSoldOut: (optionName: string) => `‘${optionName}’ 옵션이 품절돼서 주문할 수 없어요`,
    itemInactive: '지금은 판매하지 않는 메뉴예요',
    itemOptionsInvalid: '옵션을 다시 골라주세요',
    noteValidationUnavailable: '옵션 정보를 다시 불러온 뒤 주문할 수 있어요',
    noteValidating: '주문할 수 있는지 확인하고 있어요',
  },
} as const;
